# Generated by Django 3.2.12 on 2022-06-06 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catergory', models.CharField(choices=[('QnA', 'Q&A'), ('Info', '정보'), ('Talk', '잡담'), ('Notice', '공지사항')], default='Info', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_article_users', models.ManyToManyField(related_name='like_articles', to=settings.AUTH_USER_MODEL)),
                ('write_article_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_article', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commented_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment', to='articles.article')),
                ('like_comment_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_comments', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comment', to='articles.comment')),
                ('write_comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
