# Generated by Django 3.2.12 on 2022-06-07 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('checked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=20)),
                ('logo_img', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('need_skills', models.ManyToManyField(blank=True, related_name='super_skills', to='skills.Skill')),
                ('skill_list', models.ManyToManyField(through='skills.Knowledge', to=settings.AUTH_USER_MODEL)),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_skill', to='skills.type')),
            ],
        ),
        migrations.AddField(
            model_name='knowledge',
            name='knowledge_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_knowledge', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='knowledge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_knowledge', to='skills.type'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='knowledge_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_knowledge', to=settings.AUTH_USER_MODEL),
        ),
    ]
